// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcuqadixigejuglcgeae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdXFhZGl4aWdlanVnbGNnZWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODA4ODUsImV4cCI6MjA2MTU1Njg4NX0.cauWAbrpcOtmcAf8RJeSKOnqClRpwHhzqUs9zFnwFxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);